version: '3.1'

services:

  db:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myRoot
      MYSQL_DATABASE: myDB
      MYSQL_USER: myUser
      MYSQL_PASSWORD: 1234567
    networks:
      - mynetwork

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: myUser
      PMA_PASSWORD: 1234567
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
