# Macete: Toda parte de Transação com Conexão ao Banco de Dados seja resolvida na camada de serviço
# Sem conexão com Banco Aberta, transação pendente, quando for para a camada de controlador
spring.jpa.open-in-view=false

# Configurações do Banco H2
# ----------------------------------------------
# Caminho de acesso em memória
spring.datasource.url=jdbc:h2:mem:testdb 
# Usuário
spring.datasource.username=sa
# Senha
spring.datasource.password=

# Configurações do Cliente Admin do Banco H2
# Aplicação Web acessada via Browser para gerenciar o DB H2 [Vem Pronto!]
spring.h2.console.enabled=true
# Endereço
spring.h2.console.path=/h2-console

# Exibe o SQL no Terminal/Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
